controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


books:
    path: /allbooks
    controller: App\Controller\BookController::list


# Ruta para añadir nuevo libro:
newBooks:
    path: /books/new
    controller: App\Controller\AddBookController::addBooks
    method: get, post

# Ruta para eliminar un libro: 
deleteBook:
    path: /books/{id}
    controller: App\Controller\DeleteBookController::deleteBook
    method: delete